<div class="panel panel-default draggable edit-manpage-panel">
    <div class="panel-heading">
        <button id="btn-close-manpage-editor" type="button" class="close" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <button id="save-manpage" type="button" class="save" aria-label="Save"><span aria-hidden="true"><i class="glyphicon glyphicon-check"></i></span></button>
        <h3 class="panel-title"><?php echo sprintf('%s: %s', $this->translate("EDITING"), $this->manpage->getSubject()); ?></h3>
    </div>
    <div class="panel-body" style="padding: .25em;">
        <div class="form-group">
            <label for="manpage-subject">
                <input type="text" id="manpage-subject" name="manpage-subject" class="manpage-subject form-control" style="border: 0;" value="<?php echo $this->manpage->getSubject(); ?>" />
            </label>
        </div>
        <div class="form-group">
            <label for="manpage-status">
                <select id="manpage-status" name="manpage-status" class="manpage-status form-control" <?php echo (!$this->showstatusdropdown) ? 'disabled="disabled"' : ''; ?>>
                    <?php foreach (\Netrunners\Entity\Manpage::$lookup as $statusId => $statusString) : ?>
                        <option value="<?php echo $statusId; ?>" <?php echo ($this->manpage->getStatus() == $statusId) ? 'selected="selected"' : '';?>>
                            status: <?php echo $statusString; ?>
                        </option>
                    <?php endforeach; ?>
                </select>
            </label>
        </div>
        <label for="manpage-content">
            <textarea id="manpage-content" name="manpage-content" class="manpage-content" rows="12" style="border: 0; padding: .25em;"><?php echo $this->manpage->getContent(); ?></textarea>
        </label>
    </div>
</div>
<script type="application/javascript">

    $('.manpage-container')
        .css('max-height', viewportHeight*0.425)
        .css('height', viewportHeight*0.425)
        .css('max-width', viewportWidth*0.33)
        .css('width', viewportWidth*0.33)
        .css('top', viewportHeight*0.5)
        .css('left', viewportWidth*0.65);

    var editorWidth = viewportWidth*0.329 - 10;
    $('#manpage-content').css('width', editorWidth);
    $('#manpage-subject').css('width', editorWidth);

    $('#save-manpage').on('click', function(){
        var jsonData = {
            command: 'parseFrontendInput',
            subcommand: 'savemanpage',
            hash: hash,
            content: editor1.getData(),
            title: $('#manpage-subject').val(),
            status: $('#manpage-status').val(),
            entityId: <?php echo $this->manpage->getId(); ?>,
            silent: true
        };
        conn.send(JSON.stringify(jsonData));
    });

    if (!editor1) {
        editor1 = CKEDITOR.replace( 'manpage-content', {width: editorWidth, uiColor: '#3c3c3c', contentsCss: '../../../css/ckeditor.css'} );
        editor1.editorConfig = function( config ) {
            config.toolbar = [
                { name: 'basicstyles', items: [ 'Bold', 'Italic' ] },
                { name: 'paragraph', items: [ 'NumberedList', 'BulletedList', '-', 'Outdent', 'Indent' ] },
                { name: 'links', items: [ 'Link', 'Unlink', 'Anchor' ] }
            ];
        };
    }

</script>
