<a href="<?php echo $this->url('passage', ['action' => 'create']); ?>" class="btn btn-sm btn-outline-secondary"><?php echo $this->translate("Create passage"); ?></a>
<a href="" class="btn btn-sm btn-outline-secondary"><?php echo $this->translate("Create choice"); ?></a>
<a href="" class="btn btn-sm btn-outline-secondary"><?php echo $this->translate("Create character"); ?></a>
<a href="" class="btn btn-sm btn-outline-secondary"><?php echo $this->translate("Create variable"); ?></a>