<?php
/** @var \Zend\Form\Form $form */
$form = $this->form;
$form->setAttribute('action', $this->url('passage', ['action' => 'update', 'id' => $this->entity->getId()]));

/** @var \Zend\Form\Fieldset $fieldset */
$fieldset = $form->get('passage');

$title = $fieldset->get('title');
$title->setAttribute('class', 'form-control');
$title->setAttribute('placeholder', $this->translate("Passage title"));
$title->setLabel($this->translate("Title"));

$description = $fieldset->get('description');
$description->setAttribute('class', 'form-control');
$description->setAttribute('id', 'passage-description');
$description->setAttribute('placeholder', $this->translate("Passage description"));
$description->setLabel($this->translate("Description"));

$status = $fieldset->get('status');
$status->setAttribute('class', 'form-control');
$status->setLabel($this->translate("Status"));
$status->setLabelAttributes(['class' => 'control-label']);
$status->setValueOptions(\TwistyPassages\Service\PassageService::$status);

$added = $fieldset->get('added');
$added->setValue($this->entity->getAdded()->format('Y-m-d H:i:s'));

$storyElement = $fieldset->get('story');

$allowChoiceSubmissions = $fieldset->get('allowChoiceSubmissions');
$allowChoiceSubmissions->setAttribute('class', 'form-control');
$allowChoiceSubmissions->setLabel($this->translate("allow choice submissions?"));

$submit = $form->get('submit');
$submit->setAttribute('class', 'btn btn-primary');
$submit->setValue($this->translate("Edit passage"));

$form->prepare();

?>

<div class="container-fluid">
    <div class="row">

        <?php echo $this->partial('twisty-passages/partials/editor-sidebar'); ?>

        <main role="main" class="col-md-9 ml-sm-auto col-lg-10 pt-3 px-4">

            <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pb-2 mb-3 border-bottom">
                <h1 class="jumbotron-heading"><?php echo $this->translate(sprintf("Edit a passage in %s", $this->story->getTitle())); ?></h1>
                <div class="btn-toolbar mb-2 mb-md-0">
                    <div class="btn-group mr-2">
                        <?php echo $this->partial('twisty-passages/partials/editor-button-menu'); ?>
                    </div>
                </div>
            </div>

            <div class="passage-create-form py-3 bg-light">
                <div class="container-fluid">
                    <?php echo $this->form()->openTag($form); ?>
                    <div class="form-group row">
                        <div class="col-sm-8">
                            <?php echo $this->formElement($title); ?>
                            <?php echo $this->formElementErrors($title, array('class' => 'text-danger')) ?>
                        </div>
                    </div>
                    <div class="form-group row">
                        <div class=" col-sm-8">
                            <?php echo $this->formElement($description); ?>
                            <?php echo $this->formElementErrors($description, array('class' => 'text-danger')) ?>
                        </div>
                    </div>
                    <div class="form-group row">
                        <div class=" col-sm-8">
                            <?php echo $this->formLabel($status); ?>
                            <?php echo $this->formElement($status); ?>
                            <?php echo $this->formElementErrors($status, array('class' => 'text-danger')) ?>
                        </div>
                    </div>
                    <div class="form-group row">
                        <div class=" col-sm-1">
                            <?php echo $this->formElement($allowChoiceSubmissions); ?>
                            <?php echo $this->formElementErrors($allowChoiceSubmissions, array('class' => 'text-danger')) ?>
                        </div>
                        <div class=" col-sm-7">
                            <?php echo $this->formLabel($allowChoiceSubmissions); ?>
                        </div>
                    </div>
                    <?php echo $this->formHidden($storyElement); ?>
                    <?php echo $this->formHidden($added); ?>
                    <div class="row">
                        <?php echo $this->formSubmit($submit); ?>
                    </div>
                    <?php echo $this->form()->closeTag(); ?>
                </div>
            </div>

        </main>

    </div>
</div>

<script type="application/javascript">

    CKEDITOR.replace( 'passage-description', {customConfig: '../../../../js/ck_default_config.js'} );

</script>