<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('H4X0R4G3')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath('css/style.css'))
                        ->prependStylesheet($this->basePath('css/jquery.contextMenu.min.css'))
                        ->prependStylesheet($this->basePath('assets/vendor/font-awesome/css/font-awesome.min.css'))
                        ->prependStylesheet($this->basePath('assets/vendor/leaflet/css/leaflet.css'))
                        ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
                        ->prependStylesheet($this->basePath('assets/vendor/jqueryui/themes/base/menu.css'))
                        ->prependStylesheet($this->basePath('assets/vendor/jqueryui/themes/base/sortable.css'))
                        ->prependStylesheet($this->basePath('assets/vendor/jqueryui/themes/base/selectable.css'))
                        ->prependStylesheet($this->basePath('assets/vendor/jqueryui/themes/base/resizable.css'))
                        ->prependStylesheet($this->basePath('assets/vendor/jqueryui/themes/base/draggable.css'))
                        ->prependStylesheet($this->basePath('assets/vendor/jqueryui/themes/base/core.css')); ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath('js/functions.js'))
            ->prependFile($this->basePath('js/global.js'))
            ->prependFile($this->basePath('js/jquery.contextMenu.min.js'))
            ->prependFile($this->basePath('assets/vendor/leaflet/js/leaflet.min.js'))
            ->prependFile($this->basePath('js/d3.min.js'))
            ->prependFile($this->basePath('js/easeljs-0.8.2.min.js'))
            ->prependFile($this->basePath('js/soundjs-0.6.2.min.js'))
            ->prependFile($this->basePath('js/tweenjs-0.6.2.min.js'))
            ->prependFile($this->basePath('js/preloadjs-0.6.2.min.js'))
            ->prependFile($this->basePath('assets/vendor/ckeditor/ckeditor.js'))
            ->prependFile($this->basePath('js/jquery.inputHistory.js'))
            ->prependFile($this->basePath('assets/vendor/bootstrap3/js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/popper.min.js'))
            ->prependFile($this->basePath('assets/vendor/jqueryui/jquery-ui.min.js'))
            ->prependFile($this->basePath('assets/vendor/jquery/jquery.min.js'))
            ->prependFile($this->basePath('js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath('js/html5shiv.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',)); ?>

    </head>
    <body>
        <?php echo $this->content; ?>
        <?php echo $this->inlineScript() ?>
        <noscript>
            <img class="img-noscript" src="<?php echo $this->basePath('img/noscript_img.jpg'); ?>" title="NO JAVASCRIPT - NO GAME!" />
        </noscript>
        <img class="img-tesseract" src="<?php echo $this->basePath('img/8-cell-orig.gif'); ?>" title="Hi!" />
    </body>
</html>
