<?php echo $this->doctype(); ?>

<html lang="en">
<head>
    <meta charset="utf-8">
    <?php echo $this->headTitle('TWISTY PASSAGES - EDITOR')->setSeparator(' - ')->setAutoEscape(false) ?>

    <?php echo $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <!-- Le styles -->
    <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
        ->prependStylesheet($this->basePath('css/editor.css'))
        ->prependStylesheet($this->basePath('css/jquery.contextMenu.min.css'))
        ->prependStylesheet($this->basePath('assets/vendor/font-awesome/css/font-awesome.min.css'))
        ->prependStylesheet($this->basePath('assets/vendor/datatables/css/dataTables.bootstrap4.min.css'))
        ->prependStylesheet($this->basePath('assets/vendor/datatables/css/jquery.dataTables.min.css'))
        ->prependStylesheet($this->basePath('assets/vendor/bootstrap/css/bootstrap.min.css'))
        ->prependStylesheet($this->basePath('assets/vendor/jqueryui/themes/base/menu.css'))
        ->prependStylesheet($this->basePath('assets/vendor/jqueryui/themes/base/sortable.css'))
        ->prependStylesheet($this->basePath('assets/vendor/jqueryui/themes/base/selectable.css'))
        ->prependStylesheet($this->basePath('assets/vendor/jqueryui/themes/base/resizable.css'))
        ->prependStylesheet($this->basePath('assets/vendor/jqueryui/themes/base/draggable.css'))
        ->prependStylesheet($this->basePath('assets/vendor/jqueryui/themes/base/core.css')); ?>

    <!-- Scripts -->
    <?php echo $this->headScript()
        ->prependFile($this->basePath('assets/vendor/holder/holder.min.js'))
        ->prependFile($this->basePath('js/jquery.contextMenu.min.js'))
        ->prependFile($this->basePath('assets/vendor/datatables/js/dataTables.bootstrap4.min.js'))
        ->prependFile($this->basePath('assets/vendor/datatables/js/jquery.dataTables.min.js'))
        ->prependFile($this->basePath('js/d3.min.js'))
        ->prependFile($this->basePath('assets/vendor/ckeditor/ckeditor.js'))
        ->prependFile($this->basePath('assets/vendor/bootstrap/js/bootstrap.min.js'))
        ->prependFile($this->basePath('js/popper.min.js'))
        ->prependFile($this->basePath('assets/vendor/jqueryui/jquery-ui.min.js'))
        ->prependFile($this->basePath('assets/vendor/jquery/jquery.min.js'))
        ->prependFile($this->basePath('js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
        ->prependFile($this->basePath('js/html5shiv.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',)); ?>

</head>
<body>

<nav class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0">
    <a class="navbar-brand col-sm-3 col-md-2 mr-0" href="#">TWISTY PASSAGES - EDITOR</a>
    <?php if ($this->entity) : ?>
        <input class="form-control form-control-dark w-100" type="text" placeholder="Search" aria-label="Search">
    <?php endif; ?>
    <ul class="navbar-nav px-3">
        <li class="nav-item text-nowrap">
            <?php if(!$this->zfcUserIdentity()): ?>
                <a class="nav-link" href="login">Sign in</a>
            <?php else : ?>
                <a class="nav-link" href="/user/logout">Sign out</a>
            <?php endif; ?>
        </li>
    </ul>
</nav>

<div class="container-fluid">
    <?php echo $this->content; ?>
</div>

<?php echo $this->inlineScript() ?>
</body>
</html>
