<?php echo $this->doctype(); ?>

<html lang="en">
<head>
    <meta charset="utf-8">
    <?php echo $this->headTitle('H4X0R4G3 - TWISTY PASSAGES')->setSeparator(' - ')->setAutoEscape(false) ?>

    <?php echo $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <!-- Le styles -->
    <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
        ->prependStylesheet($this->basePath('css/tp-layout.css'))
        ->prependStylesheet($this->basePath('css/jquery.contextMenu.min.css'))
        ->prependStylesheet($this->basePath('assets/vendor/font-awesome/css/font-awesome.min.css'))
        ->prependStylesheet($this->basePath('assets/vendor/datatables/css/dataTables.bootstrap4.min.css'))
        ->prependStylesheet($this->basePath('assets/vendor/datatables/css/jquery.dataTables.min.css'))
        ->prependStylesheet($this->basePath('assets/vendor/bootstrap/css/bootstrap.min.css'))
        ->prependStylesheet($this->basePath('assets/vendor/jqueryui/themes/base/menu.css'))
        ->prependStylesheet($this->basePath('assets/vendor/jqueryui/themes/base/sortable.css'))
        ->prependStylesheet($this->basePath('assets/vendor/jqueryui/themes/base/selectable.css'))
        ->prependStylesheet($this->basePath('assets/vendor/jqueryui/themes/base/resizable.css'))
        ->prependStylesheet($this->basePath('assets/vendor/jqueryui/themes/base/draggable.css'))
        ->prependStylesheet($this->basePath('assets/vendor/jqueryui/themes/base/core.css')); ?>

    <!-- Scripts -->
    <?php echo $this->headScript()
        ->prependFile($this->basePath('js/tp.js'))
        ->prependFile($this->basePath('assets/vendor/holder/holder.min.js'))
        ->prependFile($this->basePath('js/jquery.contextMenu.min.js'))
        ->prependFile($this->basePath('assets/vendor/datatables/js/dataTables.bootstrap4.min.js'))
        ->prependFile($this->basePath('assets/vendor/datatables/js/jquery.dataTables.min.js'))
        ->prependFile($this->basePath('js/d3.min.js'))
        ->prependFile($this->basePath('assets/vendor/ckeditor/ckeditor.js'))
        ->prependFile($this->basePath('assets/vendor/bootstrap/js/bootstrap.min.js'))
        ->prependFile($this->basePath('js/popper.min.js'))
        ->prependFile($this->basePath('assets/vendor/jqueryui/jquery-ui.min.js'))
        ->prependFile($this->basePath('assets/vendor/jquery/jquery.min.js'))
        ->prependFile($this->basePath('js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
        ->prependFile($this->basePath('js/html5shiv.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',)); ?>

</head>
<body>

<header>
    <div class="navbar navbar-dark bg-dark box-shadow">
        <div class="container d-flex justify-content-between">
            <a href="#" class="navbar-brand d-flex align-items-center">
                <strong>H4X0R4G3 - TWISTY PASSAGES</strong>
            </a>
        </div>
    </div>
</header>

<?php echo $this->content; ?>

<footer class="footer">
    <div class="container">
    </div>
</footer>

<?php echo $this->inlineScript() ?>
</body>
</html>
