set foreign_key_checks = 0;
TRUNCATE Aivatar;
TRUNCATE Auction;
TRUNCATE BannedIp;
TRUNCATE Connection;
TRUNCATE FactionRoleInstance;
TRUNCATE File;
TRUNCATE FileModInstance;
TRUNCATE FilePartInstance;
TRUNCATE GameOptionInstance;
TRUNCATE `Group`;
TRUNCATE GroupRoleInstance;
TRUNCATE KnownNode;
TRUNCATE MailMessage;
TRUNCATE MilkrunInstance;
TRUNCATE Node;
TRUNCATE Notification;
TRUNCATE NpcInstance;
TRUNCATE Profile;
TRUNCATE ProfileEffect;
TRUNCATE ProfileFactionRating;
TRUNCATE SkillRating;
TRUNCATE System;
TRUNCATE SystemLog;
TRUNCATE User;
TRUNCATE user_role_linker;
set foreign_key_checks = 1;