<main role="main">

    <section class="jumbotron jumbotron-fluid text-center">
        <div class="container">
            <h1 class="jumbotron-heading">TWISTY PASSAGES</h1>
            <p class="lead text-muted"><?php echo $this->translate("Interactive fiction from the H4X0R4G3 game universe that also has subtle effects on your character in H4X0R4G3 itself! Please find a selection of stories below. Have fun and please consider to get involved by writing your own story."); ?></p>
            <p>
                <a href="#" class="btn btn-primary my-2"><?php echo $this->translate("Browse all stories"); ?></a>
                <a href="<?php echo $this->url('story', ['action' => 'create']); ?>" class="btn btn-secondary my-2"><?php echo $this->translate("Create a story"); ?></a>
            </p>
        </div>
    </section>

    <div class="topnine py-3 bg-light">
        <div class="container">
            <div class="row">
                <?php foreach ($this->topStories as $topStory) : ?>
                    <?php echo $this->partial('twisty-passages/partials/card', ['topStory' => $topStory]); ?>
                <?php endforeach; ?>
            </div>
        </div>
    </div>

</main>