<?php
$this->headScript()->appendScript('var wsprotocol = "' . $this->wsprotocol . '"; wshost = "' . $this->wshost . '"; wsport = "' . $this->wsport . '";');
$this->headScript()->appendFile('js/site.js');
?>
<div id="main-content" class="content">
    <div id="messages">
        <!--suppress HtmlFormInputWithoutLabel -->
        <input id="command-input" type="text" autocomplete="off" />
    </div>
</div>
<div id="3" class="notification-box btn btn-xs btn-default" onclick="playSoundByClick(this)" data-content="" data-toggle="tooltip" data-placement="left" title="Notifications"></div>
<div class="actiontime-box btn btn-xs btn-default" data-content="" data-toggle="tooltip" data-placement="left" title="Actiontimer"></div>
<div id="panel-container" class="panel-container"></div>
<div id="milkrun-container" class="milkrun-container"></div>
<input type="hidden" id="ipaddy" name="ipaddy" value="<?php echo $_SERVER['REMOTE_ADDR']; ?>" />