<div class="panel panel-default draggable manage-mails-panel">
    <div class="panel-heading">
        <button id="btn-close-manage-mails" type="button" class="close" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h3 class="panel-title"><?php echo $this->translate("manage mails"); ?></h3>
    </div>
    <div class="panel-body table-responsive" style="padding: 0;">
        <table id="mails-table" class="cell-border compact" cellspacing="0" width="100%">
            <thead>
            <tr>
                <th>ID</th>
                <th>SUBJECT</th>
                <th>AUTHOR</th>
                <th>RECEIVED</th>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($this->mails as $mail) : /** @var \Netrunners\Entity\MailMessage $mail */ ?>
                <tr data-row-id="<?php echo $mail->getId(); ?>">
                    <td>
                        <?php echo $mail->getId(); ?>
                    </td>
                    <td>
                        <?php echo $mail->getSubject(); ?>
                    </td>
                    <td>
                        <?php echo $this->mailMasterHelper()->getFromString($mail); ?>
                    </td>
                    <td>
                        <?php echo $mail->getSentDateTime()->format('Y-m-d H:i:s'); ?>
                    </td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>

<?php echo $this->headLink()->appendStylesheet('/css/nh_tables.css'); ?>

<style>
    #mails-table tbody tr {
        cursor: pointer;
    }
</style>

<script>

    $('.panel-container')
        .css('max-height', viewportHeight*0.425)
        .css('height', viewportHeight*0.425)
        .css('max-width', viewportWidth*0.33)
        .css('width', viewportWidth*0.33)
        .css('top', viewportHeight*0.5)
        .css('left', viewportWidth*0.65);

    $(document).ready(function() {

        var table = $('#mails-table').DataTable({
            "pageLength": 10
        });

        $('#mails-table tbody').on( 'click', 'tr', function () {
            if ( $(this).hasClass('selected') ) {
                $(this).removeClass('selected');
            }
            else {
                table.$('tr.selected').removeClass('selected');
                $(this).addClass('selected');
                var rowId = $(this).data('row-id');
                var command = {
                    command: 'parseInput',
                    hash: hash,
                    content: 'mailread ' + rowId
                };
                conn.send(JSON.stringify(command));
            }
        } );

    } );

</script>